name: easy_notifications
description: A Flutter plugin for handling local notifications with enhanced security and privacy features. Supports Android, iOS and Web platforms with rich customization options.
version: 1.2.1
repository: https://github.com/djungarikDEV/Easy-Notifications.git
issue_tracker: https://github.com/djungarikDEV/Easy-Notifications/issues
homepage: https://github.com/djungarikDEV/Easy-Notifications

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.5
  path: ^1.9.0
  plugin_platform_interface: ^2.1.8
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.2
  crypto: ^3.0.6
  http: ^1.3.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  test: ^1.24.9
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.djungarik.easy_notifications
        pluginClass: EasyNotificationsPlugin
      ios:
        pluginClass: EasyNotificationsPlugin
      web:
        pluginClass: EasyNotificationsWeb
        fileName: easy_notifications_web.dart
      windows:
        pluginClass: EasyNotificationsPlugin
      macos:
        pluginClass: EasyNotificationsPlugin
      linux:
        pluginClass: EasyNotificationsPlugin

topics:
  - notifications
  - scheduling
  - security
  - local-notifications
  - cross-platform
