name: easy_notifications
description: A secure Flutter plugin for local notifications with enhanced privacy features. Supports Android and iOS with customizable styles.
version: 1.0.2
repository: https://github.com/djungarikDEV/Easy-Notifications.git
issue_tracker: https://github.com/djungarikDEV/Easy-Notifications/issues
homepage: https://github.com/djungarikDEV/Easy-Notifications

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  plugin:
    platforms:
      android:
        package: com.djungarikdev.easy_notifications
        pluginClass: EasyNotificationsPlugin
      ios:
        pluginClass: EasyNotificationsPlugin

topics:
  - notifications
  - scheduling
  - security
